name: Python CI


on:
  push:
  pull_request:
    branches: [ master ]

env:
  # Private package index credentials, for installing and publishing to the private pypi index (see readme)
  PUBLISH_URL: ${{secrets.PRIVATE_PYPI_PUBLISH_URL}}
  PUBLISH_USER: ${{secrets.PRIVATE_PYPI_PUBLISH_USER}}
  PUBLISH_PASSWORD: ${{secrets.PRIVATE_PYPI_PUBLISH_PASSWORD}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.9'
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run pytest
        run: pdm run pytest

      - name: Build
        run: pdm build

      - name: Create Release from Tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: Publish to Private Package Index
        if: startsWith(github.ref, 'refs/tags/')
        run: pdm publish --repository https://${{env.PUBLISH_USER}}:${{env.PUBLISH_PASSWORD}}@pkgs.dev.azure.com/csiro-energy/csiro-energy/_packaging/csiro-python-packages/pypi/upload
