name: Python CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache PDM packages
        uses: actions/cache@v2
        with:
          path: ~/.pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Install PDM
        run: pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Run pytest
        run: pdm run pytest
