name: Python CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Cache PDM packages
        uses: actions/cache@v2
        with:
          path: ~/.pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Install PDM
        run: pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Run pytest
        run: pdm run pytest

      - name: Build
        run: pdm build

      - name: Extract version from pyproject.toml
        id: get_version
        run: echo "::set-output name=VERSION::$(grep '^version = ' pyproject.toml | sed 's/version = //g' | tr -d '\"')"

      - name: Create Release
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'
          tag: ${{ steps.get_version.outputs.VERSION }}